/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    plans: Plan;
    'tentant-subscriptions': TentantSubscription;
    tenants: Tenant;
    'tenant-users': TenantUser;
    users: User;
    customers: Customer;
    media: Media;
    devices: Device;
    products: Product;
    orders: Order;
    'order-items': OrderItem;
    entitlements: Entitlement;
    'checkin-logs': CheckinLog;
    payments: Payment;
    subscriptions: Subscription;
    'event-seats': EventSeat;
    'seat-reservations': SeatReservation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    tenants: {
      members: 'tenant-users';
      products: 'products';
      customers: 'customers';
    };
    users: {
      tenantUsers: 'tenant-users';
    };
    customers: {
      entitlements: 'entitlements';
      orders: 'orders';
      subscriptions: 'subscriptions';
      checkInLogs: 'checkin-logs';
    };
    orders: {
      items: 'order-items';
      payments: 'payments';
      seats: 'seat-reservations';
    };
    'order-items': {
      entitlements: 'entitlements';
    };
    entitlements: {
      checkInLogs: 'checkin-logs';
    };
  };
  collectionsSelect: {
    plans: PlansSelect<false> | PlansSelect<true>;
    'tentant-subscriptions': TentantSubscriptionsSelect<false> | TentantSubscriptionsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'tenant-users': TenantUsersSelect<false> | TenantUsersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    devices: DevicesSelect<false> | DevicesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    entitlements: EntitlementsSelect<false> | EntitlementsSelect<true>;
    'checkin-logs': CheckinLogsSelect<false> | CheckinLogsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'event-seats': EventSeatsSelect<false> | EventSeatsSelect<true>;
    'seat-reservations': SeatReservationsSelect<false> | SeatReservationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  name?: string | null;
  price?: number | null;
  maxStaff?: number | null;
  maxProducts?: number | null;
  maxCheckinsPerMonth?: number | null;
  features?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tentant-subscriptions".
 */
export interface TentantSubscription {
  id: number;
  tenant?: (number | null) | Tenant;
  planName: string;
  maxMembers?: number | null;
  maxEvents?: number | null;
  maxStaff?: number | null;
  price?: number | null;
  status?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug?: string | null;
  status: 'active' | 'suspended' | 'trial';
  plan?: (number | null) | Plan;
  logoUrl?: string | null;
  logoAsset?: (number | null) | Media;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  subscriptionPlan?: string | null;
  members?: {
    docs?: (number | TenantUser)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  products?: {
    docs?: (number | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  customers?: {
    docs?: (number | Customer)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  avatarAsset?: (number | null) | Media;
  isPlatformAdmin: boolean;
  status?: ('active' | 'suspended') | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  tenantUsers?: {
    docs?: (number | TenantUser)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-users".
 */
export interface TenantUser {
  id: number;
  tenant: number | Tenant;
  user: number | User;
  name?: string | null;
  email?: string | null;
  tenantName?: string | null;
  avatarAsset?: (number | null) | Media;
  role: 'owner' | 'admin' | 'staff' | 'cashier';
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  tenant: number | Tenant;
  name: string;
  descriptions?: string | null;
  productType: 'membership' | 'event' | 'package';
  price: number;
  currency: string;
  isActive?: boolean | null;
  config?: MembershipConfig | EventConfig | PackageConfig;
  thumbnailAsset?: (number | null) | Media;
  features?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface MembershipConfig {
  type: 'membership';
  duration_days: number;
  visit_limit?: number | null;
  recurring?: boolean;
  grace_period_days?: number;
  [k: string]: unknown;
}
export interface EventConfig {
  type: 'event';
  event_start: string;
  event_end: string;
  venue?: string;
  max_capacity?: number;
  allow_multiple_entry?: boolean;
  [k: string]: unknown;
}
export interface PackageConfig {
  type: 'package';
  visit_quota: number;
  expiry_days?: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  tenant: number | Tenant;
  memberId: string;
  name: string;
  email?: string | null;
  phone: string;
  gender?: ('male' | 'female') | null;
  birthDate?: string | null;
  avatarAsset?: (number | null) | Media;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  entitlements?: {
    docs?: (number | Entitlement)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  subscriptions?: {
    docs?: (number | Subscription)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  checkInLogs?: {
    docs?: (number | CheckinLog)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements".
 */
export interface Entitlement {
  id: number;
  tenant: number | Tenant;
  customer: number | Customer;
  product: number | Product;
  orderItem: number | OrderItem;
  startAt?: string | null;
  endAt?: string | null;
  remainingQuota?: number | null;
  status: 'active' | 'expired' | 'used_up' | 'cancelled';
  parentId?: (number | null) | Entitlement;
  qrCode?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  productType?: string | null;
  checkInLogs?: {
    docs?: (number | CheckinLog)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  order: number | Order;
  product: number | Product;
  invoiceNumber?: string | null;
  productName?: string | null;
  quantity?: number | null;
  price?: number | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  entitlements?: {
    docs?: (number | Entitlement)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  tenant: number | Tenant;
  customer: number | Customer;
  items?: {
    docs?: (number | OrderItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  invoiceNumber?: string | null;
  totalAmount?: number | null;
  status?: ('pending' | 'paid' | 'cancelled' | 'refunded') | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  payments?: {
    docs?: (number | Payment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  seats?: {
    docs?: (number | SeatReservation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  order: number | Order;
  method: 'cash' | 'transfer' | 'qris' | 'other';
  price?: number | null;
  status: 'paid' | 'waiting' | 'cancelled';
  paidAt?: string | null;
  referenceNumber?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seat-reservations".
 */
export interface SeatReservation {
  id: number;
  tentant: number | Tenant;
  seat: number | EventSeat;
  order: number | Order;
  status?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-seats".
 */
export interface EventSeat {
  id: number;
  tentant: number | Tenant;
  product: number | Product;
  seatCode?: string | null;
  section?: string | null;
  status: 'available' | 'reserved' | 'sold';
  note?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkin-logs".
 */
export interface CheckinLog {
  id: number;
  tentant: number | Tenant;
  customer: number | Customer;
  entitlement: number | Entitlement;
  location?: string | null;
  deviceId?: string | null;
  status: 'success' | 'rejected';
  note?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  tentant: number | Tenant;
  customer: number | Customer;
  product: number | Product;
  nextBillingDate?: string | null;
  status: 'active' | 'paused' | 'cancelled';
  paymentMethod?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices".
 */
export interface Device {
  id: number;
  name: string;
  deviceType: 'qr_scanner' | 'gate' | 'tablet';
  apiKey: string;
  lastSeen?: string | null;
  status?: string | null;
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'tentant-subscriptions';
        value: number | TentantSubscription;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'tenant-users';
        value: number | TenantUser;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'devices';
        value: number | Device;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'entitlements';
        value: number | Entitlement;
      } | null)
    | ({
        relationTo: 'checkin-logs';
        value: number | CheckinLog;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'event-seats';
        value: number | EventSeat;
      } | null)
    | ({
        relationTo: 'seat-reservations';
        value: number | SeatReservation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  maxStaff?: T;
  maxProducts?: T;
  maxCheckinsPerMonth?: T;
  features?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tentant-subscriptions_select".
 */
export interface TentantSubscriptionsSelect<T extends boolean = true> {
  tenant?: T;
  planName?: T;
  maxMembers?: T;
  maxEvents?: T;
  maxStaff?: T;
  price?: T;
  status?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  plan?: T;
  logoUrl?: T;
  logoAsset?: T;
  meta?: T;
  isDeleted?: T;
  deletedAt?: T;
  subscriptionPlan?: T;
  members?: T;
  products?: T;
  customers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-users_select".
 */
export interface TenantUsersSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  name?: T;
  email?: T;
  tenantName?: T;
  avatarAsset?: T;
  role?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatarAsset?: T;
  isPlatformAdmin?: T;
  status?: T;
  meta?: T;
  isDeleted?: T;
  deletedAt?: T;
  tenantUsers?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  tenant?: T;
  memberId?: T;
  name?: T;
  email?: T;
  phone?: T;
  gender?: T;
  birthDate?: T;
  avatarAsset?: T;
  meta?: T;
  entitlements?: T;
  orders?: T;
  subscriptions?: T;
  checkInLogs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices_select".
 */
export interface DevicesSelect<T extends boolean = true> {
  name?: T;
  deviceType?: T;
  apiKey?: T;
  lastSeen?: T;
  status?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  descriptions?: T;
  productType?: T;
  price?: T;
  currency?: T;
  isActive?: T;
  config?: T;
  thumbnailAsset?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  meta?: T;
  isDeleted?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  tenant?: T;
  customer?: T;
  items?: T;
  invoiceNumber?: T;
  totalAmount?: T;
  status?: T;
  meta?: T;
  payments?: T;
  seats?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  invoiceNumber?: T;
  productName?: T;
  quantity?: T;
  price?: T;
  meta?: T;
  entitlements?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements_select".
 */
export interface EntitlementsSelect<T extends boolean = true> {
  tenant?: T;
  customer?: T;
  product?: T;
  orderItem?: T;
  startAt?: T;
  endAt?: T;
  remainingQuota?: T;
  status?: T;
  parentId?: T;
  qrCode?: T;
  meta?: T;
  productType?: T;
  checkInLogs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checkin-logs_select".
 */
export interface CheckinLogsSelect<T extends boolean = true> {
  tentant?: T;
  customer?: T;
  entitlement?: T;
  location?: T;
  deviceId?: T;
  status?: T;
  note?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  order?: T;
  method?: T;
  price?: T;
  status?: T;
  paidAt?: T;
  referenceNumber?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  tentant?: T;
  customer?: T;
  product?: T;
  nextBillingDate?: T;
  status?: T;
  paymentMethod?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-seats_select".
 */
export interface EventSeatsSelect<T extends boolean = true> {
  tentant?: T;
  product?: T;
  seatCode?: T;
  section?: T;
  status?: T;
  note?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seat-reservations_select".
 */
export interface SeatReservationsSelect<T extends boolean = true> {
  tentant?: T;
  seat?: T;
  order?: T;
  status?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
